---
info:
  description: This is rest api for Checksheets
  version: 1.0.0
host: localhost:3000
basePath: /api/v1
produces:
  - application/json
schemes:
  - http
  - https
securityDefinitions: {}
swagger: '2.0'
paths:
  '/checksheet':
    post:
      parameters:
        - name: machineName
          in: get
          description: The name of the equipment being check
          required: false
          type: string
        - name: supervisor
          in: get
          description: Your supervisor
          required: false
          type: string
        - name: completedBy
          in: get
          description: Who wrote up this sheet
          required: false
          type: string
        - name: date
          in: get
          description: '-'
          required: false
          type: date
        - name: checks
          in: get
          description: A list of checks that should be done
          required: false
          type: Array.Check
      description: create a CheckSheet
      tags:
        - Checksheet
      responses:
        '201':
          description: |-
            successfully created comment
            /
  '/checksheets':
    get:
      parameters: []
      description: Get a list of all comments related to specific idea
      tags:
        - Checksheet
      responses:
        '200':
          description: |-
            A list of comments
            /
          schema:
            type: array
            items:
              '$ref': '#/definitions/Checksheet'
  '/checksheets/:id':
    get:
      parameters:
        - name: id
          in: path
          description: id of the Checksheet in the route URL
          required: true
          type: string
      description: Get a single checksheet based on id
      tags:
        - Checksheet
      responses:
        '200':
          description: returns a checksheet
        '500':
          description: |-
            Internal server error
            /
  '/checksheet/:id':
    delete:
      parameters:
        - name: id
          in: path
          description: id of the Checksheet in the route URL
          required: true
          type: string
      description: Delete a Checksheet
      tags:
        - Checksheet
      responses:
        '200':
          description: Successfully deleted comment
definitions:
  Checksheet:
    required:
    properties:
      _id:
        type: string
        description: unique identifier generated by MongoDB
      machineName:
        type: string
        description: The name of the equipment being check
      supervisor:
        type: string
        description: Your supervisor
      completedBy:
        type: string
        description: Who wrote up this sheet
      date:
        type: date
        description: ''
      checks:
        type: Array.Check
        description: A list of checks that should be done
      null-null:
        type: Array.Comment
        description: a list comments
  Comment:
    required:
      - text
    properties:
      _id:
        type: string
        description: unique identifier generated by MongoDB
      text:
        type: string
        description: the comment
      createdBy:
        type: String
        description: the Person who this comment
      createdAt:
        type: date
        description: ''
  Check:
    required:
      - Description
    properties:
      _id:
        type: string
        description: unique identifier generted by MongoDB
      Description:
        type: string
        description: what is being checked on the equipment
      status:
        type: string
        description: The result of the check { ok, not, job raised}
      createdAt:
        type: date
        description: The Date of when the check was done
responses: {}
parameters: {}
tags:
  - name: Checksheet
    description: ''
